mode: ips
interface: eth0
nfqueue:
  queue_num: 0
networks:
  home_net: "172.21.0.0/24"
  external_net: "any"
rules:
  file: "/workspace/config/rules/local.rules"
logging:
  alert_file: "/var/log/minisnort/alert.log"
  level: info
